# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:4.6.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # Install app requirements
          - npm install
          # Testing app
          - npm test         
          # Install python requirements
          - apt-get update -y
          - apt-get install -y python-pip unzip
          # Configuration environment variables
          - export CLOUDSDK_CORE_PROJECT=$(cat gcp/CLOUDSDK_CORE_PROJECT)          
          - export GOOGLE_CLIENT_SECRET=$(cat gcp/GOOGLE_CLIENT_SECRET.json)
          - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
          # Install Google Cloud SDK is pinned for build reliability. Bump if the SDK complains about deprecation.
          - SDK_VERSION=138.0.0
          - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          - curl -O -J https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          - tar -zxvf ${SDK_FILENAME} --directory ${HOME}
          - export PATH=${PATH}:${HOME}/google-cloud-sdk/bin          
          # Configure Google Cloud SDK
          - gcloud auth activate-service-account --key-file gcp/GOOGLE_CLIENT_SECRET.json      
          # Finish deploy (--log-http --verbosity=debug) 
          - gcloud config set project ${CLOUDSDK_CORE_PROJECT}        
          - gcloud --quiet --verbosity=error app deploy app.yaml --promote 